{
 "title": "Pizza Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "Source",
    "query": "jwt-pizza-service, jwt-pizza-service-dev"
   }
  ]
 },
 "panels": [
  {
   "title": "New Panel",
   "type": "table",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{component=\"jwt-pizza-service\"} |= `` | json"
    }
   ]
  },
  {
   "title": "HTTP requests/minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(requests_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "all"
    },
    {
     "expr": "rate(requests_get_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(requests_post_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "post"
    },
    {
     "expr": "rate(requests_put_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(requests_delete_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "delete"
    }
   ]
  },
  {
   "title": "Request Latencies",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(request_latency_milliseconds{source=\"jwt-pizza-service\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pizza Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizzas_sold_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizzas sold (/minute)"
    },
    {
     "expr": "rate(pizza_creation_failures_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Pizza creation failures (/minute)"
    }
   ]
  },
  {
   "title": "Revenue (/minute)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 7, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(revenue_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Bitcoin"
    }
   ]
  },
  {
   "title": "Pizza Creation Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "rate(pizza_purchase_latency_milliseconds{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "active_tokens_count_ratio{source=\"jwt-pizza-service\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Auth Attempts (per minute)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 24 },
   "targets": [
    {
     "expr": "rate(auth_success_count_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "Success"
    },
    {
     "expr": "rate(auth_failure_count_total{source=\"jwt-pizza-service\"}[1m])",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 11, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "cpu_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 15, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "memory_usage_percent{source=\"jwt-pizza-service\"}",
     "legendFormat": "Memory"
    }
   ]
  }
 ]
}